### ISSUE TITLE
Plugin doesn't work with Gradle 2.2.1

### ISSUE THREAD

**Issue by tbroyer** [nebula-plugins/nebula-dependency-recommender#2]
Apparently Gradle no longer uses/bundles Apache Commons.

```
:core:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify dependency resolution listener.
> org/apache/commons/lang/StringUtils

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.listener.ListenerNotificationException: Failed to notify dependency resolution listener.
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:94)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy19.beforeResolve(Unknown Source)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:249)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:240)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:442)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:205)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
[…]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin$1$1$1.execute(DependencyRecommendationsPlugin.java:33)
	at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin$1$1$1.execute(DependencyRecommendationsPlugin.java:29)
	at org.gradle.listener.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:109)
	at org.gradle.listener.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:98)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	... 75 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
	... 80 more
```

After I add:
```
    classpath 'commons-lang:commons-lang:2.6'
    classpath 'commons-io:commons-io:2.4'
```
to the buildscript's dependencies, I get errors resolving parent POMs for `mavenBom`:
```
Exception while polling provider recommender-13 for version
java.lang.IllegalArgumentException: no model resolver provided, cannot resolve parent POM org.jboss.resteasy:resteasy-jaxrs-all:3.0.10.Final for POM org.jboss.resteasy:resteasy-bom:3.0.10.Final
	at org.gradle.mvn3.org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:805)
	at org.gradle.mvn3.org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:664)
	at org.gradle.mvn3.org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:310)
	at org.gradle.mvn3.org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
	at netflix.nebula.dependency.recommender.provider.MavenBomRecommendationProvider.getVersion(MavenBomRecommendationProvider.java:38)
	at netflix.nebula.dependency.recommender.RecommendationProviderContainer.getRecommendedVersion(RecommendationProviderContainer.java:98)
	at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin.getRecommendedVersionRecursive(DependencyRecommendationsPlugin.java:71)
	at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin.getRecommendedVersionRecursive(DependencyRecommendationsPlugin.java:77)
	at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin$1$1$2.execute(DependencyRecommendationsPlugin.java:51)
	at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin$1$1$2.execute(DependencyRecommendationsPlugin.java:39)
	at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:78)
	at org.gradle.api.internal.artifacts.ivyservice.VersionForcingDependencyToModuleResolver.resolve(VersionForcingDependencyToModuleResolver.java:39)
[…]
```

**Comment by rspieldenner** [comment]
I believe we're in the process of making sure all of these work with 2.2.1 currently. Should be working shortly.

**Comment by tbroyer** [comment]
Thanks. Any ETA yet? Days? Weeks?

**Comment by rspieldenner** [comment]
Days

**Comment by jkschneider** [comment]
Fixed with 3bc464 in release 2.0.2 available in JCenter.

**Comment by tbroyer** [comment]
Hours ;-)

I doubt it's enough though: I had issues with Commons I/O, and then resolving Maven BOMs.

**Comment by tbroyer** [comment]
Just checked 2.0.2 this morning (UTC+1) and I confirm it still doesn't work with Gradle 2.2.1; I still see `NoClassDefFoundError` on `org/apache/commons/io/IOUtils`, and if I add commons-io to the classpath, I then still have the `no model resolver provided, cannot resolve parent POM` error.

Here's my (stripped down) `build.gradle`:

```groovy
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath 'com.netflix.nebula:nebula-dependency-recommender:2.0.2'
  }
}

allprojects {
  apply plugin: 'nebula-dependency-recommender'

  repositories {
    mavenCentral()
  }
}

dependencyRecommendations {
  mavenBom module: 'org.jooq:jooq-parent:3.5.1'
  mavenBom module: 'org.jboss.resteasy:resteasy-bom:3.0.10.Final'
  map recommendations: [
      'mysql:mysql-connector-java': '5.1.34'
  ]
}
```

And then in a subproject:

```groovy
apply plugin: 'java'

dependencies {
  compile 'org.jooq:jooq'
  runtime 'mysql:mysql-connector-java'
}
```

**Comment by jkschneider** [comment]
@tbroyer - fixed with commit 18e0aae3 on the gradle-2.2 branch.  Upgrade to 2.2.1 to take advantage.  Sorry that took so long - the old and shaded version of Aether that is baked into Gradle is particularly hard to work with...
